name: build docs

on: 
  workflow_dispatch: 
#  push: 
#    branches: 
#      - "main"

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 

        - name: Checkout code
          uses: actions/checkout@v3
          with: 
            ref: main

        - name: Setup node 16
          uses: actions/setup-node@v3
          with:
            node-version: 16

        - name: Install dependencies and build docs
          run: |
            yarn install
            yarn run build
            echo "akelite.sherkey.ml" > src/.vuepress/dist/CNAME

        - name: Get current date
          id: date
          run: echo "::set-output name=today::$(TZ=UTC-8 date +"%Y-%m-%d %T")"


        - name: Push changes to branch gh-pages
          uses: s0/git-publish-subdir-action@develop
          env:
            REPO: self
            BRANCH: gh-pages
            FOLDER: src/.vuepress/dist
            GITHUB_TOKEN: ${{ secrets.DEPLOY_KEY }}
            SQUASH_HISTORY: true
            MESSAGE: "Site update from commit {sha} with the message [{msg}]"