name: build docs

on: 
  workflow_dispatch: 
  push: 
    branches: 
      - "main"

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 

        - name: Checkout code
          uses: actions/checkout@v3
          with: 
            ref: main

        - name: Setup node 16
          uses: actions/setup-node@v3
          with:
            node-version: 16

        - name: Install dependencies
          if: steps.cache-node-modules.outputs.cache-hit != 'true'
          run: yarn install

        - name: Cache node_modules
          uses: actions/cache@v3
          id: cache-node-modules # use this to check for `cache-hit` (`steps.cache-node-modules.outputs.cache-hit != 'true'`)
          with:
            path: node_modules
            key: ${{ runner.os }}-${{ matrix.node-version }}-nodeModules-${{ hashFiles('yarn.lock') }}-${{ hashFiles('package.json') }}
            restore-keys: |
              ${{ runner.os }}-${{ matrix.node-version }}-nodeModules-

        - name: Build docs
          run: yarn run build

        - name: Commit and push to branch gh-pages
          run: |
            rm -rf .git
            cd src/.vuepress/dist
            git init && git add .
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git commit -m "Site update on: $(date -d "today" + "%Y-%m-%d %H:%M:%S")"

        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.DEPLOY_KEY }}
            branch: gh-pages
            force: true